version: '3'

volumes:
  postgres_volume:

services:
  minio:
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"  # API порт
      - "${MINIO_UI_PORT}:9001"  # Web интерфейс (консоль управления)
    volumes:
      - /Users/nastya/Documents/GitHub/fish-services/minio_data:/data  # Хранилище данных (можно заменить на свой путь)
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"  # Логин (измените на свой)
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"  # Пароль (обязательно измените!)
    command: server /data --console-address ":9001"  # Запуск сервера с консолью
    #restart: unless-stopped  # Автоматический перезапуск
  pg_test:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5666:5432"
    volumes:
      - /Users/nastya/Documents/GitHub/fish-services/user/db-migration/test/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /Users/nastya/Documents/GitHub/fish-services/test_data:/var/lib/postgresql/data

  migrator_test:
    build:
      context: .
      dockerfile: db-migration/test/migrations.test.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg_test
