
volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: db-migration/migrations.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      DB_HOST: pg
      PG_DSN: "postgres://${PG_USER}:${PG_PASSWORD}@pg:5432/${PG_DATABASE_NAME}?sslmode=disable"
      MINIO_DSN: "${MINIO_HOST}:9000"
      MINIO_USER_SERVICE_ACCESS_KEY: "${MINIO_USER_SERVICE_ACCESS_KEY}"
      MINIO_USER_SERVICE_SECRET_KEY: "${MINIO_USER_SERVICE_SECRET_KEY}"
      RMQ_DSN: "amqp://${RMQ_USER}:${RMQ_PASSWORD}@${RMQ_HOST}:5672/"
      GRPC_HOST: "${GRPC_HOST}"
      GRPC_PORT: "${GRPC_PORT}"
    depends_on:
      - pg